server:
  port: 9999
eureka:
  instance:
    hostname: localhost
  client:
    # 向注册中心注册服务
    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: spring-cloud-eureka