server:
  port: 9998
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://localhost:9999/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/xinsmile/cloud-config-repo.git
#          username:
#          passphrase:
          searchPaths: /**
#          searchPaths: '{application}'
#security:
#  basic:
#    enabled: true
#  user:
#    #这是config-server的用户名和密码
#    name: root
#    password: booszy